server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gms-user
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  config:
    name: gms-user-service
  mvc:
    view:
      prefix: classpath:templates/pages
      suffix: .html
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
