server:
  port: 8003
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gms_orders?useUnicode=true&characterEncoding=utf8
    username: root
    password:
  cloud:
    zookeeper:
      connect-string: localhost:2181
  application:
    name: gms-order-server
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
