server:
  port: 8004
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gms-shopping-car?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    zookeeper:
      connect-string: 192.168.1.23:2181
  config:
    name: gms-shopping-car-server

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
