server:
  port: 8002
spring:
  application:
    name: gms-pro-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gms-pro
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    zookeeper:
      connect-string: 192.168.1.23:2181

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
