server:
  port: 8002
spring:
  application:
    name: gms-pro-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gms-pro
    username: root
    password:
  cloud:
    zookeeper:
      connect-string: localhost:2181

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
